-- Ejemplo de JOINS 1

SELECT COUNTRY_NAME 
    FROM HR.COUNTRIES c, HR.REGIONS r
	WHERE c.REGION_ID = r.REGION_ID AND REGION_NAME='Americas';

-- Ejemplo de JOINS 2

SELECT CITY 
    FROM HR.LOCATIONS a, HR.COUNTRIES b, HR.REGIONS c
	WHERE a.COUNTRY_ID=b.COUNTRY_ID 
    	AND b.REGION_ID = c.REGION_ID 
    	AND	REGION_NAME='Americas';